[package]
name = "shallow-water"
version = "0.1.0"
authors = ["Ferdia McKeogh <ferdia@mckeogh.tech>"]
edition = "2018"

[profile.release]
lto = "fat"
panic = "abort"
debug = true
overflow-checks = false

[dependencies]
ndarray = { version = "0.13.0", features = ["approx", "rayon"] }
log = "0.4.8"
clap = "2.33.0"
byteorder = "1.3.4"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_yaml = "0.8.11"
quit = "1.0.0"
rayon = "1.3.0"
jemallocator = "0.3.2"

[dev-dependencies]
insta = "0.16.0"
byteorder = "1.3.4"
approx = "0.3.2"
lazy_static = "1.4.0"
criterion = "0.3.1"

[[bench]]
name = "spectral"
harness = false

[[bench]]
name = "sta2dfft"
harness = false

[[bench]]
name = "stafft"
harness = false

[[bench]]
name = "setup"
harness = false

[[bench]]
name = "nhswps"
harness = false
